dist: trusty
sudo: false

language: scala

jdk: oraclejdk8

script: sbt ^test ^package

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "qfquJGncsHNaiXj0bfXIoPfTTMdkf7oAU8yv54aRbi6CZPPX+IWwuUJe+V4SC1lnBcOcOHfvGbysKYvZhZA+AoVAZFZnN3dDM4du28oUJo7JS+LHM7YfP9zRLqlHXIa/b+MGA6IfRTDvTihK9ZO/iYEbbGBprCBJcwFeM3AH+H0iQXPrhJlZPBqmCIYlvph+AF9oK41ZNIlDW+jZkQTv2Ftf9sOYc+VFLrNDsLKavuN5rqEpQRqqqyQe2MlM7GZimigkLT23br6KgZjpc6fucfJDr4cKZm0AwWy4pxQzTsqJthiJBnMnpqPVxT7yUWrwdySoo8Nl+NYAE4PmhFVG50B+gVL1bwiI3AS+Np7ks+G88kGiJ2kXjJpvehV6W35NIzUZO7uJXgjNSOeQ7WrOPub0RSM8IOl+RSk/EyiIJphV/yGoqJNmFG933W0y0yX7dx1CNfPxfNjnsJmpda2uvdrxOV83ZPiEed61VUsocynOGMP/w3RIKf3kudB9/6pvOa2mdfP/5QosCi/CFuYoMxjE6TSxOA4w/4ifbSzW4iyM1k4tu/0MGmtlKiFtAuMDXpLuG0nwW5tmDOiJ07tmXfWIi8wZaOd5ED4RS+oAfY+FqUbHnimXYHXfy//FZ5iaqpWF2uucPNr7LcQkrbCq4UWZmIWso0ut73YM2SidR8Q="

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete